spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdatabase?characterEncoding=utf8&useSSL=false
    username: root
    password: zxsgdsg612057
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mybatis/**Mapper.xml