spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogsystem?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Zxsgdsg6125057
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mybatis/**Mapper.xml